services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - sonarr_config:/config
      - sonarr_tv:/tv
      - sonarr_downloads:/downloads
    ports:
      - "8989"
    restart: unless-stopped
    labels:
      yantr.app: "sonarr"
      yantr.service: "Smart PVR for TV show monitoring and automated downloading with Usenet and BitTorrent"

volumes:
  sonarr_config:
    name: sonarr_config
  sonarr_tv:
    name: sonarr_tv
  sonarr_downloads:
    name: sonarr_downloads
