services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.4-master
    container_name: kokoro
    labels:
      yantr.app: "kokoro"
      yantr.service: "Text-to-Speech"
    ports:
      - "8880"
    restart: unless-stopped
