services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.4-master
    container_name: kokoro
    labels:
      yantr.app: "kokoro"
      yantr.service: "Kokoro"
      yantr.info: "Lightweight Text-to-Speech model with 82M parameters delivering high-quality speech synthesis"
    ports:
      - "8880"
    restart: unless-stopped
