services:
  ttyd-alphine:
    image: tsl0922/ttyd:alpine
    container_name: ttyd-alphine
    labels:
      yantr.app: "ttyd-alphine"
      yantr.service: "Share your terminal over the web â€” runs a bash shell in Alpine Linux accessible from any browser"
    ports:
      - "7681"
    restart: unless-stopped
