services:
  ttyd-alphine:
    image: tsl0922/ttyd:alpine
    container_name: ttyd-alphine
    labels:
      yantr.app: "ttyd-alphine"
      yantr.service: "Web Terminal"
    ports:
      - "7681"
    restart: unless-stopped
