services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    labels:
      yantr.app: "stirling-pdf"
      yantr.service: "Stirling-PDF"
      yantr.info: "Powerful locally hosted web-based PDF manipulation tool"
    ports:
      - "8080"
    volumes:
      - stirling_pdf_data:/usr/share/tessdata
      - stirling_pdf_config:/configs
    environment:
      DOCKER_ENABLE_SECURITY: ${STIRLING_PDF_SECURITY:-false}
      SYSTEM_DEFAULTLOCALE: ${STIRLING_PDF_LOCALE:-en-US}
    restart: unless-stopped

volumes:
  stirling_pdf_data:
  stirling_pdf_config:
