services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    labels:
     yantra.name: "Stirling-PDF"
     yantra.logo: "QmNhu7w75WnED5iZSjQfBCbqw1H9cnijkdKFvAUWrbffwi"
     yantra.category: "tools,utility"
     yantra.port: "8085 (HTTP - Web UI)"
     yantra.description: "Powerful locally hosted web-based PDF manipulation tool"
     yantra.website: "https://github.com/Stirling-Tools/Stirling-PDF"
     yantra.github: "https://github.com/Stirling-Tools/Stirling-PDF"
    ports:
      - "8085:8080"
    volumes:
      - stirling_pdf_data:/usr/share/tessdata
      - stirling_pdf_config:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=${STIRLING_PDF_SECURITY:-false}
      - SYSTEM_DEFAULTLOCALE=${STIRLING_PDF_LOCALE:-en-US}
    restart: unless-stopped

volumes:
  stirling_pdf_data:
  stirling_pdf_config:
