services:
  gotify:
    image: ghcr.io/gotify/server
    container_name: gotify
    labels:
      yantr.app: "gotify"
      yantr.service: "Notifications"
    ports:
      - "80"
    environment:
      GOTIFY_DEFAULTUSER_NAME: ${GOTIFY_DEFAULTUSER_NAME:-admin}
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS:-admin}
    volumes:
      - gotify_data:/app/data
    restart: unless-stopped

volumes:
  gotify_data:
