services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    labels:
     yantra.name: "Vaultwarden"
     yantra.logo: "QmYSoiyanJ26mbB4CVZXGNEk1tfGjNaEnf3hBQyhtgA85w"
     yantra.category: "productivity,security"
     yantra.port: "80"
     yantra.description: "Lightweight Bitwarden server for password management"
     yantra.website: "https://github.com/dani-garcia/vaultwarden/wiki"
     yantra.github: "https://github.com/dani-garcia/vaultwarden"
    ports:
      - "8000:80"
    volumes:
      - vaultwarden_data:/data
    environment:
      - WEBSOCKET_ENABLED=true
    restart: unless-stopped

volumes:
  vaultwarden_data:
