services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    labels:
     yantra.name: "Vaultwarden"
     yantra.logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/vaultwarden.png"
     yantra.category: "productivity"
     yantra.port: "80"
     yantra.description: "Lightweight Bitwarden server for password management"
     yantra.website: "https://github.com/dani-garcia/vaultwarden/wiki"
     yantra.github: "https://github.com/dani-garcia/vaultwarden"
     yantra.tags: "passwords,security,bitwarden,encryption"
    ports:
      - "8000:80"
    volumes:
      - vaultwarden_data:/data
    environment:
      - WEBSOCKET_ENABLED=true
    restart: unless-stopped

volumes:
  vaultwarden_data:
