services:
  domain-locker:
    image: lissy93/domain-locker:latest
    container_name: domain-locker
    hostname: domain-locker
    volumes:
      - domain_locker_data:/app/data
    ports:
      - "3000"
    restart: unless-stopped
    labels:
      yantr.app: "domain-locker"
      yantr.service: "Domain Monitor"

volumes:
  domain_locker_data:
