services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    environment:
      AUTO_UPDATE: "true"
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - "9117"
    restart: unless-stopped
    labels:
      yantr.app: "jackett"
      yantr.service: "Torrent Indexer"

volumes:
  jackett_config:
  jackett_downloads:
