services:
  dashmachine:
    image: rmountjoy/dashmachine:latest
    container_name: dashmachine
    labels:
      yantr.app: "dashmachine"
      yantr.service: "Bookmarks"
    ports:
      - "5000"
    volumes:
      - dashmachine_data:/dashmachine/dashmachine/user_data
    restart: unless-stopped

volumes:
  dashmachine_data:
