services:
  airsonic:
    image: lscr.io/linuxserver/airsonic:latest
    container_name: airsonic
    labels:
      yantr.app: "airsonic"
      yantr.service: "Music Streaming"
    ports:
      - "4040"
    volumes:
      - airsonic_config:/config
      - airsonic_music:/music
      - airsonic_playlists:/playlists
      - airsonic_podcasts:/podcasts
      - airsonic_media:/media
    restart: unless-stopped

volumes:
  airsonic_config:
  airsonic_music:
  airsonic_playlists:
  airsonic_podcasts:
  airsonic_media:
