services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    labels:
      yantra.name: "Watchtower"
      yantra.logo: "QmfCtZ3ij2PgQxv5pn5ymEFCgQiyiSXfvZnfk4LzCjr4NG"
      yantra.category: "tools,utility"
      yantra.description: "Automatically update running Docker containers"
      yantra.website: "https://containrrr.dev/watchtower"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=10800
    restart: unless-stopped
