services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    labels:
     yantra.name: "Watchtower"
     yantra.logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/watchtower.png"
     yantra.category: "tools"
     yantra.description: "Automatically update running Docker containers"
     yantra.website: "https://containrrr.dev/watchtower"
     yantra.github: "https://github.com/containrrr/watchtower"
     yantra.tags: "automation,updates,containers,maintenance"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
    restart: unless-stopped
