services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    volumes:
      - jellyfin-config:/config
      - jellyfin-tvshows:/data/tvshows
      - jellyfin-movies:/data/movies
    ports:
      - "8096"
    restart: unless-stopped
    labels:
      yantra.name: "Jellyfin"
      yantra.logo: "QmacujPMRLrMPjWkCLHr3gyQniejcXtkc3LpaJ5YQqZLUD"
      yantra.category: "media,entertainment"
      yantra.port: "8096 (HTTP - Web UI)"
      yantra.description: "Free and open-source media server for streaming video, music, and photos"
      yantra.website: "https://jellyfin.org/"

volumes:
  jellyfin-config:
    name: jellyfin-config
  jellyfin-tvshows:
    name: jellyfin-tvshows
  jellyfin-movies:
    name: jellyfin-movies
