services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    volumes:
      - jellyfin-config:/config
      - jellyfin-media:/data
    ports:
      - "8096"
    restart: unless-stopped
    labels:
      yantr.app: "jellyfin"
      yantr.service: "Free and open-source media server for streaming video, music, and photos"

volumes:
  jellyfin-config:
    name: jellyfin-config
  jellyfin-media:
    name: jellyfin-media
