services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    volumes:
      - swingmusic-music:/music
      - swingmusic-config:/config
    ports:
      - "1970"
    restart: unless-stopped
    labels:
      yantr.app: "swingmusic"
      yantr.service: "SwingMusic"
      yantr.info: "Beautiful music player with a modern web interface"

volumes:
  swingmusic-music:
    name: swingmusic-music
  swingmusic-config:
    name: swingmusic-config
