services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    volumes:
      - swingmusic-music:/music
      - swingmusic-config:/config
    ports:
      - "1970"
    restart: unless-stopped
    labels:
      yantra.name: "SwingMusic"
      yantra.logo: "QmVWKyW9G8C4zxCDMMutg7eSNuugdAzUUNwzhbvjkv6j1o"
      yantra.category: "media,entertainment"
      yantra.port: "1970 (HTTP - Web UI)"
      yantra.description: "Beautiful music player with a modern web interface"
      yantra.website: "https://swingmusic.vercel.app/"

volumes:
  swingmusic-music:
    name: swingmusic-music
  swingmusic-config:
    name: swingmusic-config
