services:
  openclaw:
    image: ghcr.io/getumbrel/openclaw-umbrel:2026.2.26
    container_name: openclaw
    labels:
      yantr.app: "openclaw"
      yantr.service: "AI Assistant"
    init: true
    restart: unless-stopped
    ports:
      - "18789"
      - "18790"
    volumes:
      - openclawdata:/data
      - openclawlinuxbrew:/home/linuxbrew

volumes:
  openclawdata:
  openclawlinuxbrew:
