services:
  openclaw:
    image: ghcr.io/getumbrel/openclaw-umbrel:2026.2.3
    container_name: openclaw
    labels:
      yantra.name: "OpenClaw"
      yantra.logo: "Qma5h9Xquf4PKQczQHpZSVyUoevXQPV7vkTDr2Y6vUwcGm"
      yantra.category: "tools,utility"
      yantra.port: "18789 (HTTP - Web UI)"
      yantra.description: "Self-hosted development environment and container management tool"
      yantra.website: "https://github.com/getumbrel/openclaw-umbrel"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "18789"
    volumes:
      - openclaw_data:/data
      - openclaw_linuxbrew:/home/linuxbrew

volumes:
  openclaw_data:
  openclaw_linuxbrew:
