services:
  opnform:
    image: jhumanj/opnform:latest
    container_name: opnform
    labels:
      yantr.app: "opnform"
      yantr.service: "Form Builder"
    ports:
      - "80"
    volumes:
      - opnform_persist:/persist
    restart: unless-stopped

volumes:
  opnform_persist:
