services:
  streambox:
    image: ghcr.io/besoeasy/streambox:main
    container_name: streambox
    labels:
     yantra.name: "StreamBox"
     yantra.logo: "QmVdbRUyvZpXCsVJAs7fo1PJPXaPHnWRtSCFx6jFTGaG5i"
     yantra.category: "media,tools"
     yantra.port: "6798 (HTTP - Web UI), 6799 (HTTP - DOWNLOADS)"
     yantra.description: "Media streaming and sharing platform with Telegram integration"
     yantra.website: "https://github.com/besoeasy/streambox"
     yantra.github: "https://github.com/besoeasy/streambox"
    ports:
      - "6798:6798"
      - "6799:6799"
      - "4445:4445"
      - "6888:6888/tcp"
      - "6888:6888/udp"
    environment:
      - TELEGRAMBOT=${STREAMBOX_TELEGRAMBOT}
      - NSEC=${STREAMBOX_NSEC}
      - AUTHCODE=${STREAMBOX_AUTHCODE}
    volumes:
      - streambox_data:/tmp/streambox
    restart: unless-stopped

volumes:
  streambox_data:
