services:
  appsmith:
    image: appsmith/appsmith-ce:latest
    container_name: appsmith
    labels:
      yantr.app: "appsmith"
      yantr.service: "Low-Code Platform"
    ports:
      - "80"
      - "443"
    volumes:
      - appsmith_stacks:/appsmith-stacks
    restart: unless-stopped

volumes:
  appsmith_stacks:
