services:
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    volumes:
      - emby-config:/config
      - emby-media:/data
    ports:
      - "8096"
    restart: unless-stopped
    labels:
      yantr.app: "emby"
      yantr.service: "Media server for streaming video, music, live TV, and photos"

volumes:
  emby-config:
    name: emby-config
  emby-media:
    name: emby-media
