services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    labels:
      yantr.app: "n8n"
      yantr.service: "Automation"
    ports:
      - "5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      N8N_PORT: 5678
    restart: unless-stopped

volumes:
  n8n_data:
