services:
  droppy:
    image: silverwind/droppy:latest
    container_name: droppy
    labels:
      yantr.app: "droppy"
      yantr.service: "Lightweight self-hosted file manager and sharing solution"
    ports:
      - "8989"
    volumes:
      - droppy_config:/config
      - droppy_files:/files
    restart: unless-stopped

volumes:
  droppy_config:
  droppy_files:
