services:
  invio:
    image: ghcr.io/kittendevv/invio:latest
    container_name: invio
    labels:
      yantr.app: "invio"
      yantr.service: "Invio"
      yantr.info: "Self-hosted invoicing without the bloat"
    ports:
      - "3000"
    volumes:
      - invio_data:/app/data
    restart: unless-stopped

volumes:
  invio_data:
