services:
  smokeping:
    image: linuxserver/smokeping:latest
    container_name: smokeping
    labels:
      yantr.app: "smokeping"
      yantr.service: "Network Monitor"
    ports:
      - "80"
    volumes:
      - smokeping_config:/config
      - smokeping_data:/data
    restart: unless-stopped

volumes:
  smokeping_config:
  smokeping_data:
