services:
  tabby:
    image: parksauce/tabby:latest
    container_name: tabby
    labels:
      yantr.app: "tabby"
      yantr.service: "Beautiful and customizable browser start page with tab management"
    ports:
      - "80"
    depends_on:
      - tabby-db
    restart: unless-stopped

  tabby-db:
    image: linuxserver/mariadb:latest
    container_name: tabby_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tabby
      MYSQL_USER: tabby
      MYSQL_PASSWORD: tabby
    volumes:
      - tabby_db:/config
    restart: unless-stopped

    labels:
      yantr.app: "tabby"
      yantr.service: "Tabby Db service for Tabby"
volumes:
  tabby_db:
