services:
  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:v0.10
    container_name: bitmagnet
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - "3333"
      - "3334/tcp"
      - "3334/udp"
    environment:
      HOME: /tmp
      XDG_CONFIG_HOME: /config
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresx
      POSTGRES_NAME: bitmagnet
    volumes:
      - bitmagnet_config:/config/bitmagnet
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      yantr.app: "bitmagnet"
      yantr.service: "Torrent Indexer"

  postgres:
    image: postgres:16-alpine
    container_name: bitmagnet_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgresx
      POSTGRES_DB: bitmagnet
      POSTGRES_USER: postgres
    shm_size: 1g
    volumes:
      - bitmagnet_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 20s
      interval: 10s

    labels:
      yantr.app: "bitmagnet"
      yantr.service: "Database"
volumes:
  bitmagnet_config:
  bitmagnet_db:
