services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - memos_data:/var/opt/memos
    ports:
      - 5230
    labels:
      yantr.app: "memos"
      yantr.service: "Open-source Markdown notes app, with a UI styled like a social feed."

volumes:
  memos_data:
