services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - radarr_config:/config
      - radarr_movies:/movies
      - radarr_downloads:/downloads
    ports:
      - "7878"
    restart: unless-stopped
    labels:
      yantr.app: "radarr"
      yantr.service: "Movie PVR"

volumes:
  radarr_config:
    name: radarr_config
  radarr_movies:
    name: radarr_movies
  radarr_downloads:
    name: radarr_downloads
