services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - radarr_config:/config
      - radarr_movies:/movies
      - radarr_downloads:/downloads
    ports:
      - "7878"
    restart: unless-stopped
    labels:
      yantra.name: "Radarr"
      yantra.logo: "QmUDQj3YeSMqCEiY2eZSWX5AR9CBWvT7PBZGJhurQJvzTX"
      yantra.category: "media,tools"
      yantra.port: "7878 (HTTP - Web UI)"
      yantra.description: "Smart PVR for movie collection management and automated downloads"
      yantra.website: "https://github.com/linuxserver/docker-radarr"

volumes:
  radarr_config:
    name: radarr_config
  radarr_movies:
    name: radarr_movies
  radarr_downloads:
    name: radarr_downloads
