services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    hostname: metube
    volumes:
      - metube_downloads:/downloads
    ports:
      - "8081"
    restart: unless-stopped
    labels:
      yantra.name: "MeTube"
      yantra.logo: "QmVHF6jueKh11T7LVbBC6NCCs2tuMo7Af7tKfWJEdXSkwQ"
      yantra.category: "media,tools,utility"
      yantra.port: "8081 (HTTP - Web UI)"
      yantra.description: "Web GUI for yt-dlp/youtube-dl with playlist support."
      yantra.website: "https://github.com/alexta69/metube"

volumes:
  metube_downloads:
