services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    hostname: metube
    volumes:
      - metube_downloads:/downloads
    ports:
      - "8081"
    restart: unless-stopped
    labels:
      yantr.app: "metube"
      yantr.service: "Video Downloader"

volumes:
  metube_downloads:
