services:
  actual-budget:
    image: actualbudget/actual-server:latest
    container_name: actual-budget
    labels:
      yantr.app: "actual-budget"
      yantr.service: "Budget App"
    ports:
      - "5006"
    volumes:
      - actual_data:/data
    restart: unless-stopped

volumes:
  actual_data:
