services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard-home
    labels:
      yantr.app: "adguard-home"
      yantr.service: "Ad Blocker"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "80"
      - "443"
      - "853:853/tcp"
      - "3000"
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    restart: unless-stopped

volumes:
  adguard_work:
  adguard_conf:
