services:
  element:
    image: vectorim/element-web:latest
    container_name: element
    labels:
      yantr.app: "element"
      yantr.service: "Chat Client"
    ports:
      - "80"
    volumes:
      - element_config:/app/config
    restart: unless-stopped

volumes:
  element_config:
