services:
  myspeed:
    image: germannewsmaker/myspeed:latest
    container_name: myspeed
    hostname: myspeed
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - myspeed_data:/myspeed/data
    ports:
      - "5216:5216"
    restart: unless-stopped
    labels:
      yantra.name: "MySpeed"
      yantra.logo: "Qma15zxYfVUTVMdxAdnCEwWHemLCEWon2pGUjs8rG56VvZ"
      yantra.category: "network,tools"
      yantra.port: "5216 (HTTP - Web UI)"
      yantra.description: "Speed test analysis software that tracks your internet speed for 30 days"
      yantra.website: "https://myspeed.dev"
      yantra.github: "https://github.com/gnmyt/myspeed"

volumes:
  myspeed_data:
