services:
  myspeed:
    image: germannewsmaker/myspeed:latest
    container_name: myspeed
    hostname: myspeed
    volumes:
      - myspeed_data:/myspeed/data
    ports:
      - "5216"
    restart: unless-stopped
    labels:
      yantr.app: "myspeed"
      yantr.service: "Speed test analysis software that tracks your internet speed for 30 days"

volumes:
  myspeed_data:
