services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    labels:
      yantr.app: "mariadb"
      yantr.service: "MariaDB"
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
