services:
  trip:
    image: ghcr.io/itskovacs/trip:latest
    container_name: trip
    labels:
      yantr.app: "trip"
      yantr.service: "Trip"
      yantr.info: "Self-hostable map tracker and trip planner to visualize POIs and organize your next adventure"
    ports:
      - "8000"
    volumes:
      - trip_storage:/app/storage
    restart: unless-stopped

volumes:
  trip_storage:
