services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    labels:
      yantr.app: "searxng"
      yantr.service: "Meta Search"
    ports:
      - "8080"
    volumes:
      - searxng_data:/etc/searxng
    environment:
      SEARXNG_BASE_URL: http://localhost:8080
    restart: unless-stopped

volumes:
  searxng_data:
