services:
  stremio:
    image: stremio/server:latest
    container_name: stremio
    restart: unless-stopped
    ports:
      - "11470"
      - "12470" # HTTPS port
    volumes:
      - stremio-data:/root/.stremio-server
    environment:
      NO_CORS: 1
      HTTPS: 1
    labels:
      yantra.name: "Stremio"
      yantra.logo: "QmUJ8LsjmfsZdPybvXWkAJsEJYadr8D6L1iqXvgtC48hfX"
      yantra.category: "media,streaming"
      yantra.port: "11470 (HTTP - Server), 12470 (HTTPS - Server)"
      yantra.description: "Media center application for streaming movies, TV shows, and video content"
      yantra.website: "https://github.com/Stremio/stremio-web"

volumes:
  stremio-data:
