services:
  jotty:
    image: ghcr.io/fccview/jotty:1.20.0
    container_name: jotty
    labels:
      yantr.app: "jotty"
      yantr.service: "Tasks"
    ports:
      - "3000"
    volumes:
      - jotty_data:/app/data
      - jotty_config:/app/config
      - jotty_cache:/app/.next/cache
    environment:
      NODE_ENV: production
    restart: unless-stopped

volumes:
  jotty_data:
  jotty_config:
  jotty_cache:
