services:
  fireshare:
    image: shaneisrael/fireshare:latest
    container_name: fireshare
    labels:
      yantr.app: "fireshare"
      yantr.service: "Video Share"
    ports:
      - "80"
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      SECRET_KEY: ${SECRET_KEY:-changeme}
      MINUTES_BETWEEN_VIDEO_SCANS: ${MINUTES_BETWEEN_VIDEO_SCANS:-60}
    volumes:
      - fireshare_data:/data
      - fireshare_processed:/processed
      - fireshare_videos:/videos
    restart: unless-stopped

volumes:
  fireshare_data:
  fireshare_processed:
  fireshare_videos:
