services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - prowlarr_config:/config
    ports:
      - "9696"
    restart: unless-stopped
    labels:
      yantra.name: "Prowlarr"
      yantra.logo: "QmVVhTMs4pxJpK91vaHE1uhX57SHPU13kKCNFuYzapmhmL"
      yantra.category: "media,tools"
      yantra.port: "9696 (HTTP - Web UI)"
      yantra.description: "Indexer manager for automating and integrating Usenet and torrent indexers"
      yantra.website: "https://github.com/linuxserver/docker-prowlarr"

volumes:
  prowlarr_config:
    name: prowlarr_config
