services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - prowlarr_config:/config
    ports:
      - "9696"
    restart: unless-stopped
    labels:
      yantr.app: "prowlarr"
      yantr.service: "Indexer Manager"

volumes:
  prowlarr_config:
    name: prowlarr_config
