services:
  ttyd-ubuntu:
    image: tsl0922/ttyd:latest
    container_name: ttyd-ubuntu
    labels:
      yantr.app: "ttyd-ubuntu"
      yantr.service: "Web Terminal"
    ports:
      - "7681"
    restart: unless-stopped
