services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    labels:
      yantr.app: "privatebin"
      yantr.service: "Pastebin"
    ports:
      - "8080"
    volumes:
      - privatebin_data:/srv/data
      - privatebin_config:/srv/cfg
    restart: unless-stopped

volumes:
  privatebin_data:
  privatebin_config:
