services:
  specter-desktop:
    image: ghcr.io/cryptoadvance/specter-desktop:v2.1.1
    container_name: specter-desktop
    labels:
      yantr.app: "specter-desktop"
      yantr.service: "Bitcoin Wallet"
    ports:
      - "25441"
    restart: unless-stopped
