services:
  filedrop:
    image: ghcr.io/besoeasy/file-drop:main
    container_name: filedrop
    hostname: filedrop
    environment:
      - STORAGE_MAX=${STORAGE_MAX:-200GB}
      - NPUB=${FILEDROP_NPUB:-NOSTR_PUBLIC_KEY_HERE}
    volumes:
      - filedrop_data:/app/data
    ports:
      - "3232:3232"
      - "4001:4001/tcp"
      - "4001:4001/udp"
    restart: unless-stopped
    labels:
      yantra.name: "File Drop"
      yantra.logo: "QmRXThtTrA56JhncJEPXjJBBwpu74NxbYCsHxnnkn1QQcq"
      yantra.category: "utility,tools"
      yantra.port: "3232 (HTTP - Web UI)"
      yantra.description: "Decentralized file-sharing solution for Nostr and the web."
      yantra.website: "https://github.com/besoeasy/file-drop"
      yantra.github: "https://github.com/besoeasy/file-drop"

volumes:
  filedrop_data:
