services:
  urlwatch:
    image: mediadepot/urlwatch:master
    container_name: urlwatch
    labels:
      yantra.name: "UrlWatch"
      yantra.logo: "QmWkNcdYSyueiheQwyHXyjkXrxcGdKLcYGBbcECLiJ6c3W"
      yantra.category: "utility,monitoring"
      yantra.port: "8081 (HTTP - Web UI)"
      yantra.description: "Monitor websites for changes and receive notifications on updates"
      yantra.website: "https://github.com/thp/urlwatch"
    ports:
      - "8081"
    volumes:
      - urlwatch_config:/srv/urlwatch/config
    restart: unless-stopped

volumes:
  urlwatch_config:
