services:
  urlwatch:
    image: mediadepot/urlwatch:master
    container_name: urlwatch
    labels:
      yantr.app: "urlwatch"
      yantr.service: "URL Monitor"
    ports:
      - "8081"
    volumes:
      - urlwatch_config:/srv/urlwatch/config
    restart: unless-stopped

volumes:
  urlwatch_config:
