

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    ports:
      - "${WHOAMI_PORT:-8081}:80"
    restart: unless-stopped
    labels:
     yantra.name: "Whoami"
     yantra.logo: "https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png"
     yantra.category: "utility"
     yantra.port: "${WHOAMI_PORT:-8081}"
     yantra.description: "Tiny HTTP service that prints system information - perfect for testing"
     yantra.website: "https://github.com/traefik/whoami"
     yantra.github: "https://github.com/traefik/whoami"
     yantra.tags: "testing, http, utility"

