services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    labels:
      yantra.name: "Uptime Kuma"
      yantra.logo: "Qmb7LeUwFtcWpkpbiyzEPYPecX8iXNZMtvjag9WyrCDmLV"
      yantra.category: "tools,network"
      yantra.port: "3001 (HTTP - Web UI)"
      yantra.description: "Self-hosted uptime monitoring tool"
      yantra.website: "https://github.com/louislam/uptime-kuma/wiki"
    ports:
      - "3001"
    volumes:
      - uptime_kuma_data:/app/data
    restart: unless-stopped

volumes:
  uptime_kuma_data:
