services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    labels:
     yantra.name: "Uptime Kuma"
     yantra.logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/uptime-kuma.png"
     yantra.category: "tools"
     yantra.port: "3001"
     yantra.description: "Self-hosted uptime monitoring tool"
     yantra.website: "https://github.com/louislam/uptime-kuma/wiki"
     yantra.github: "https://github.com/louislam/uptime-kuma"
     yantra.tags: "monitoring,uptime,alerts,status"
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data
    restart: unless-stopped

volumes:
  uptime_kuma_data:
