services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-downloads:/downloads
    ports:
      - "8080"
      - "6881"
      - "6881/udp"
    restart: unless-stopped
    labels:
      yantra.name: "qBittorrent"
      yantra.logo: "QmU3rohmjuaXYNe37FDEcG2P6BL8t4fzu4WvNA69voFteA"
      yantra.category: "download,network"
      yantra.port: "8080 (HTTP - Web UI), 6881 (TCP - Torrent), 6881 (UDP - Torrent)"
      yantra.description: "Feature-rich BitTorrent client with integrated search engine and web interface"
      yantra.website: "https://github.com/linuxserver/docker-qbittorrent"

volumes:
  qbittorrent-config:
    name: qbittorrent-config
  qbittorrent-downloads:
    name: qbittorrent-downloads
