services:
  remote-torrent-downloader:
    image: ghcr.io/besoeasy/remote-torrent-downloader:latest
    container_name: remote-torrent-downloader
    labels:
      yantr.app: "remote-torrent-downloader"
      yantr.service: "Media streaming and sharing platform with Telegram integration"
    ports:
      - "6798"
      - "6799"
      - "4445"
      - "6888/tcp"
      - "6888/udp"
    environment:
      TELEGRAMBOT: ${TELEGRAM_BOT_TOKEN}
      NSEC: ${NOSTR_NSEC}
      AUTHCODE: ${AUTHCODE}
    volumes:
      - remote-torrent-downloader_data:/tmp/remote-torrent-downloader
    restart: unless-stopped

volumes:
  remote-torrent-downloader_data: