services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - FB_USERNAME=${FB_USERNAME:-admin}
      - FB_PASSWORD=${FB_PASSWORD:-admin}
    volumes:
      - filebrowser_data:/database
      - filebrowser_config:/config
      - filebrowser_srv:/srv
    ports:
      - "8082:80"
    restart: unless-stopped
    labels:
      yantra.name: "File Browser"
      yantra.logo: "QmebPcQTwXvzUG4sG2X9mCZ3raT12fKXDovocFYKyTVs9j"
      yantra.category: "tools,utility"
      yantra.port: "8082 (HTTP - Web UI)"
      yantra.description: "Web-based file manager with a user-friendly interface"
      yantra.website: "https://filebrowser.org/"

volumes:
  filebrowser_data:
  filebrowser_config:
  filebrowser_srv:
