services:
  drupal:
    image: drupal:latest
    container_name: drupal
    labels:
      yantr.app: "drupal"
      yantr.service: "Powerful open-source content management system for building websites"
    ports:
      - "80"
    volumes:
      - drupal_html:/var/www/html
    restart: unless-stopped

volumes:
  drupal_html:
