services:
  nano:
    image: linuxserver/nano:latest
    container_name: nano
    labels:
      yantra.name: "Nano"
      yantra.logo: "Qmf4kNnrTW6jAtNGrhM62yC1XmvXf2x5ZtxcUfZUinegca"
      yantra.category: "cryptocurrency,blockchain"
      yantra.port: "8075 (HTTP - RPC API)"
      yantra.description: "Open source, green cryptocurrency and peer-to-peer payment system"
      yantra.website: "https://github.com/linuxserver/docker-nano"
    ports:
      - "8075"
      - "3000"
      - "3001"
    environment:
      PEER_HOST: ${PEER_HOST:-}
      LIVE_GENESIS_PUB: ${LIVE_GENESIS_PUB:-}
      LIVE_GENESIS_ACCOUNT: ${LIVE_GENESIS_ACCOUNT:-}
      LIVE_GENESIS_WORK: ${LIVE_GENESIS_WORK:-}
      LIVE_GENESIS_SIG: ${LIVE_GENESIS_SIG:-}
      CLI_OPTIONS: ${CLI_OPTIONS:-}
      LMDB_BOOTSTRAP_URL: ${LMDB_BOOTSTRAP_URL:-}
    volumes:
      - nano_config:/config
    restart: unless-stopped

volumes:
  nano_config:
