services:
  zeronote:
    image: ghcr.io/besoeasy/zeronote:main
    container_name: zeronote
    hostname: zeronote
    volumes:
      - zeronote_data:/app/data
    ports:
      - "8000"
    restart: unless-stopped
    labels:
      yantra.name: "ZeroNote"
      yantra.logo: "Qmbdks6yn4TrP2hfFZJ1dZPW84kYhrWoXDj4tLBtpWfRiF"
      yantra.category: "productivity,security"
      yantra.port: "8000 (HTTP - Web UI)"
      yantra.description: "Offline-first encrypted notes application."
      yantra.website: "https://github.com/besoeasy/zeronote"

volumes:
  zeronote_data:
