services:
  originless:
    image: ghcr.io/besoeasy/originless:main
    container_name: originless
    hostname: originless
    environment:
      STORAGE_MAX: ${STORAGE_MAX:-200GB}
    volumes:
      - originless:/app/data
    ports:
      - "3232"
      - "4001" # Swarm TCP
      - "4001/udp" # Swarm UDP
    restart: unless-stopped
    labels:
      yantra.name: "Originless"
      yantra.logo: "QmWMCDAFxDjqfYRjjaqRx4UCt7ZF9TK6r5SpZEWWko9c63"
      yantra.category: "utility,tools"
      yantra.port: "3232 (HTTP - Web UI)"
      yantra.description: "All-in-one anonymous storage backend for apps, screenshot tools, and file hosting"
      yantra.website: "https://github.com/besoeasy/originless"

volumes:
  originless:
