services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    entrypoint: /app/entrypoint.sh
    labels:
      yantr.app: "pihole"
      yantr.service: "DNS Sinkhole"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80"
    environment:
      WEBPASSWORD: ${WEBPASSWORD:-yantr}
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh:ro
      - pihole_data:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

volumes:
  pihole_data:
  pihole_dnsmasq:
