services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wireguard
    hostname: wireguard
    volumes:
      - wireguard_data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      yantr.app: "wireguard"
      yantr.service: "VPN"

volumes:
  wireguard_data:
