services:
  rotki:
    image: rotki/rotki:latest
    container_name: rotki
    labels:
     yantra.name: "Rotki"
     yantra.logo: "QmTRLwvRfA3n2Fnj8JoqUcoPXRVeNLYqk7TRqKhAq94SjE"
     yantra.category: "productivity,security,utility"
     yantra.port: "8084 (HTTP - Web UI)"
     yantra.description: "Privacy-focused portfolio tracker and analytics for crypto"
     yantra.website: "https://rotki.com/"
     yantra.github: "https://github.com/rotki/rotki"
    ports:
      - "8084:80"
    volumes:
      - rotki_data:/data
    environment:
      - TZ=${TZ:-UTC}
    restart: unless-stopped

volumes:
  rotki_data:
