services:
  rotki:
    image: rotki/rotki:latest
    container_name: rotki
    labels:
      yantr.app: "rotki"
      yantr.service: "Crypto Portfolio"
    ports:
      - "80"
    volumes:
      - rotki_data:/data
    restart: unless-stopped

volumes:
  rotki_data:
