services:
  libreddit:
    image: ceramicwhite/libreddit:0.22.9
    container_name: libreddit
    labels:
      yantr.app: "libreddit"
      yantr.service: "Reddit Client"
    ports:
      - "7420"
    environment:
      PORT: 7420
    init: true
    restart: unless-stopped
