services:
  libreddit:
    image: ceramicwhite/libreddit:0.22.9
    container_name: libreddit
    labels:
      yantra.name: "LibReddit"
      yantra.logo: "QmTieAKkWAmA12gchbEJiBGZZK64hsuKQYRtSbibJ9qWxF"
      yantra.category: "social,privacy"
      yantra.port: "7420 (HTTP - Web UI)"
      yantra.description: "Private Reddit front-end written in Rust with no JavaScript, ads, or tracking"
      yantra.website: "https://github.com/spikecodes/libreddit"
    ports:
      - "7420"
    environment:
      PORT: 7420
    init: true
    restart: unless-stopped
