services:
  alist:
    image: ghcr.io/alistgo/alist:latest
    container_name: alist
    volumes:
      - alist_data:/opt/alist/data
    ports:
      - "5244:5244"
    restart: unless-stopped
    labels:
      yantra.name: "AList"
      yantra.logo: "QmRbsgnFM5EX4SD9Mv9LsmEWJMkeXH2LoFtH8w6PEFodLP"
      yantra.category: "storage,productivity"
      yantra.port: "5244 (HTTP - Web UI)"
      yantra.description: "A file list program supporting multiple storage providers"
      yantra.website: "https://alistgo.com/"

volumes:
  alist_data:
