services:
  libreoffice:
    image: linuxserver/libreoffice:latest
    container_name: libreoffice
    hostname: libreoffice
    volumes:
      - libreoffice_config:/config
    ports:
      - "8093:3000"
      - "8094:3001"
    restart: unless-stopped
    shm_size: "1gb"
    labels:
      yantra.name: "LibreOffice"
      yantra.logo: "QmUCiKb8BvKqA9BssyndDvp9b46uU5LR7fLBpv2bkzdE78"
      yantra.category: "productivity,tools"
      yantra.port: "8093 (HTTPS - Web UI), 8094 (HTTPS - Admin)"
      yantra.description: "Full-featured office suite accessible through web browser."
      yantra.website: "https://www.libreoffice.org"
      yantra.github: "https://github.com/linuxserver/docker-libreoffice"

volumes:
  libreoffice_config:
