services:
  networking-toolbox:
    image: lissy93/networking-toolbox:latest
    container_name: networking-toolbox
    labels:
      yantr.app: "networking-toolbox"
      yantr.service: "100+ offline-first networking tools and utilities"
    ports:
      - "3000"
    restart: unless-stopped
