services:
  networking-toolbox:
    image: lissy93/networking-toolbox:latest
    container_name: networking-toolbox
    labels:
     yantra.name: "Networking Toolbox"
     yantra.logo: "QmeqFmwTVCvsBghUj1nRWCzcW4d197Gaud4iuTdGuv8KEf"
     yantra.category: "network,tools"
     yantra.port: "8096 (HTTP - Web UI)"
     yantra.description: "100+ offline-first networking tools and utilities"
     yantra.website: "https://networking-toolbox.as93.net"
     yantra.github: "https://github.com/Lissy93/networking-toolbox"
    ports:
      - "8096:3000"
    environment:
      - TZ=${TZ:-UTC}
    restart: unless-stopped
