services:
  pi-alert:
    image: jokobsk/pi.alert:latest
    container_name: pi-alert
    labels:
      yantr.app: "pi-alert"
      yantr.service: "Network monitoring tool for detecting new devices and security alerts"
    ports:
      - "20211/udp"
    volumes:
      - pi_alert_config:/config
    restart: unless-stopped

volumes:
  pi_alert_config:
