services:
  convertx:
    image: ghcr.io/c4illin/convertx:latest
    container_name: convertx
    labels:
      yantr.app: "convertx"
      yantr.service: "File Converter"
    ports:
      - "3000"
    restart: unless-stopped
