services:
  just-download:
    image: codeberg.org/highghlow/just-download:v1.0.9
    container_name: just-download
    labels:
      yantr.app: "just-download"
      yantr.service: "Just. Download."
      yantr.info: "Simple torrent downloader that bridges Torznab indexers with Transmission"
    ports:
      - "5000"
    volumes:
      - just-download_config:/config
    environment:
      LOCK_TRANSMISSION_CONFIG: 1
      CONFIG_LOCATION: /config/config.json
      CONFIG: '{"indexers": [], "transmission": {"host": "transmission_server_1", "port": 9091}}'
    restart: unless-stopped

volumes:
  just-download_config:
