services:
  just-download:
    image: codeberg.org/highghlow/just-download:v1.0.9
    container_name: just-download
    labels:
      yantra.name: "Just. Download."
      yantra.logo: "Qmc9ChgqKxSUXJ37gC8ndutwEmzCic4QQrgTaxPCffuV6V"
      yantra.category: "media"
      yantra.port: "5000 (HTTP - Web UI)"
      yantra.description: "Simple torrent downloader that bridges Torznab indexers with Transmission"
      yantra.website: "https://codeberg.org/highghlow/just-download"
    ports:
      - "5000"
    volumes:
      - just-download_config:/config
    environment:
      LOCK_TRANSMISSION_CONFIG: 1
      CONFIG_LOCATION: /config/config.json
      CONFIG: '{"indexers": [], "transmission": {"host": "transmission_server_1", "port": 9091}}'
    restart: unless-stopped

volumes:
  just-download_config:
