services:
  pastefy:
    image: interaapps/pastefy:latest
    container_name: pastefy
    labels:
      yantr.app: "pastefy"
      yantr.service: "Pastefy"
      yantr.info: "Feature-rich self-hosted pastebin for sharing code"
    ports:
      - "80"
    volumes:
      - pastefy_data:/app/data
    restart: unless-stopped

volumes:
  pastefy_data:
