services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${WEBPASSWORD:-minioadmin}
      TZ: ${TZ:-UTC}
    volumes:
      - minio_data:/data
    labels:
      yantra.name: "MinIO"
      yantra.logo: "QmbHbop4JXmJEbg6gSKuRw36UL1mmpo9z832B6KZPtJcxD"
      yantra.category: "utility,tools"
      yantra.port: "9001 (HTTP - Console), 9000 (HTTP - API)"
      yantra.description: "High Performance Object Storage compatible with Amazon S3 API"
      yantra.website: "https://min.io"
      yantra.github: "https://github.com/minio/minio"

volumes:
  minio_data:
