services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    volumes:
      - syncthing_data:/var/syncthing
    ports:
      - "8384:8384" # Web UI
      - "22000:22000/tcp" # Sync TCP
      - "22000:22000/udp" # Sync UDP
      - "21027:21027/udp" # Discovery
    restart: unless-stopped
    labels:
      yantra.name: "Syncthing"
      yantra.logo: "QmXjiuL2tgJYmbLa5rZz117MqGX49xpYbUdRrcjFrtj2Na"
      yantra.category: "tools,utility"
      yantra.port: "8384 (HTTP - Web UI)"
      yantra.description: "Continuous file synchronization program. It synchronizes files between two or more computers."
      yantra.website: "https://syncthing.net/"
      yantra.github: "https://github.com/syncthing/syncthing"

volumes:
  syncthing_data:
