services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    volumes:
      - syncthing_data:/var/syncthing
    ports:
      - "8384" # Web UI
      - "22000/tcp" # Sync TCP
      - "22000/udp" # Sync UDP
      - "21027/udp" # Discovery
    restart: unless-stopped
    labels:
      yantr.app: "syncthing"
      yantr.service: "File Sync"

volumes:
  syncthing_data:
