services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    labels:
      yantr.app: "glances"
      yantr.service: "System Monitor"
    ports:
      - "61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: "host"
    environment:
      GLANCES_OPT: -w
    restart: unless-stopped
