services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate --protocol http2 run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    labels:
      yantra.name: "Cloudflared"
      yantra.logo: "QmasRb3gavdQhKQKo5UhttEbLaMhV52AM71XahpFn7FgTb"
      yantra.category: "network,security"
      yantra.description: "Cloudflare Tunnel for secure remote access without exposing ports"
      yantra.website: "https://github.com/cloudflare/cloudflared"
