services:
  sshwifty:
    image: niruix/sshwifty:latest
    container_name: sshwifty
    ports:
      - "8182"
    restart: unless-stopped
    labels:
      yantra.name: "Sshwifty"
      yantra.logo: "QmVe73bVFRDukScD9oaptfisA21NyZAtRDLbSE74oFKcHE"
      yantra.category: "network,tools"
      yantra.port: "8182 (HTTP - Web UI)"
      yantra.description: "Browser-based SSH and Telnet client with a single-page web UI"
      yantra.website: "https://github.com/niruix/sshwifty"
