services:
  snort:
    image: voidic/snort:v0.3.0
    container_name: snort
    labels:
      yantr.app: "snort"
      yantr.service: "Nostr Client"
    ports:
      - "8080"
    init: true
    restart: unless-stopped
