services:
  youtubedl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    labels:
      yantr.app: "youtubedl-material"
      yantr.service: "Video Downloader"
    ports:
      - "17442"
    volumes:
      - youtubedl_appdata:/app/appdata
      - youtubedl_video:/app/video
      - youtubedl_subscriptions:/app/subscriptions
      - youtubedl_users:/app/users
      - youtubedl_audio:/app/audio
    restart: unless-stopped

volumes:
  youtubedl_appdata:
  youtubedl_video:
  youtubedl_subscriptions:
  youtubedl_users:
  youtubedl_audio:
