services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - heimdall-config:/config
    ports:
      - "80"
    restart: unless-stopped
    labels:
      yantr.app: "heimdall"
      yantr.service: "Home Dashboard"

volumes:
  heimdall-config:
