services:
  freshrss:
    image: linuxserver/freshrss:latest
    container_name: freshrss
    labels:
      yantr.app: "freshrss"
      yantr.service: "RSS Reader"
    ports:
      - "80"
    volumes:
      - freshrss_config:/config
    restart: unless-stopped

volumes:
  freshrss_config:
