services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "25565"
    environment:
      EULA: ${EULA:-TRUE}
      TYPE: ${TYPE:-VANILLA}
      VERSION: ${VERSION:-LATEST}
      MEMORY: ${MEMORY:-1G}
      DIFFICULTY: ${DIFFICULTY:-normal}
      MODE: ${MODE:-survival}
      MAX_PLAYERS: ${MAX_PLAYERS:-20}
      MOTD: ${MOTD:-A Minecraft Server}
    volumes:
      - minecraft-data:/data
    restart: unless-stopped
    labels:
      yantr.app: "minecraft"
      yantr.service: "Game Server"

volumes:
  minecraft-data:
