services:
  tor-browser:
    image: domistyle/tor-browser
    container_name: tor-browser
    ports:
      - "5800"
    labels:
      yantra.name: "Tor Browser"
      yantra.logo: "QmaVTPSKHnzenoUpqydsnNHQ45WJDtRxxjnqzVqK4MiB38"
      yantra.description: "Privacy-focused web browser with Tor network integration"
      yantra.category: "privacy,security"
      yantra.port: "5800 (HTTP - Web UI)"
      yantra.website: "https://github.com/domistyle/docker-tor-browser"
