services:
  tor-browser:
    image: domistyle/tor-browser
    container_name: tor-browser
    ports:
      - "5800"
    labels:
      yantr.app: "tor-browser"
      yantr.service: "Privacy-focused web browser with Tor network integration"
